<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LTPUSNY2127380" name="com.stta.SuiteThree.SuiteThreeCaseOne" tests="1" failures="0" timestamp="23 Dec 2016 05:44:09 GMT" time="0.013" errors="1">
  <testcase name="TC_01_TestCase" time="0.013" classname="com.stta.SuiteThree.SuiteThreeCaseOne">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: TC_01_TestCase([])
Arguments: [(java.lang.Integer)0,(java.util.HashMap){TestNGTestName=SuiteThree_TestCase1, Iteration=, Pass/Fail/Skip=PASS, TestCaseName=TC_01_TestCase, Data 2 Column=5, DataToRun=y, Data 3 Column=7, Expected Result=21, Data 1 Column=9}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: TC_01_TestCase([])
Arguments: [(java.lang.Integer)0,(java.util.HashMap){TestNGTestName=SuiteThree_TestCase1, Iteration=, Pass/Fail/Skip=PASS, TestCaseName=TC_01_TestCase, Data 2 Column=5, DataToRun=y, Data 3 Column=7, Expected Result=21, Data 1 Column=9}]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1238)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- TC_01_TestCase -->
</testsuite> <!-- com.stta.SuiteThree.SuiteThreeCaseOne -->
